name: CI

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy?'
        required: false
        default: 'false'
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./
          file: ./Dockerfile
          push: ${{ github.event.inputs.deploy == 'true' }}
          tags: dzoukr/podvocasem:latest, dzoukr/podvocasem:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy == 'true'
    steps:
      - name: Deploy web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'podvocasem-web'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'dzoukr/podvocasem:${{ github.sha }}'