name: Client

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy?'
        required: false
        default: 'false'
  push:
    branches: [ master ]
    paths:
      - 'src/PodVocasem.Client/**'
      - 'src/PodVocasem.Shared/**'
      - '.github/workflows/Client.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.100

      - name: Install Tools
        run: dotnet tool restore

      - name: Restore Nuget
        run: dotnet paket restore

      - name: Build
        run: dotnet run PublishClient

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-fe
          path: publish/app-fe

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy == 'true'
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: app-fe
          path: app-fe
      - name: Setup config
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: app-fe/configuration.js
          contents: |
            const config = {
                baseUrl : "https://podvocasem-web.azurewebsites.net/"
            }
          write-mode: overwrite
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'app-fe'
          output_location: ''
          skip_app_build: true
