name: Server

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy?'
        required: false
        default: 'false'
  push:
    branches: [ master ]
    paths:
      - 'src/PodVocasem.Server/**'
      - 'src/PodVocasem.Shared/**'
      - '.github/workflows/Server.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.100

      - name: Install Tools
        run: dotnet tool restore

      - name: Restore Nuget
        run: dotnet paket restore

      - name: Build
        run: dotnet run PublishServer

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: publish/app

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy == 'true'
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: app
          path: app
      - name: Deploy to FunctionApp
        uses: Azure/functions-action@v1.4.4
        with:
          app-name: podvocasem-web
          package: app
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
